
version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
      - image: circleci/mongodb:latest
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run seed
          command: npm run seed
      - run:
          name: Run tests
          command: npm test
workflows:
  sample:
    jobs:
      - build-and-test